os: linux

# we use the R VM because it contains LaTeX and pandoc
language: r
#Speed up install
cache: packages 

# Get bibtex
addons:
  apt:
    packages:
    - texlive-bibtex-extra

before_install:
  - tlmgr install etoolbox
  - tlmgr install biblatex
  - tlmgr install bibtex8
  - tlmgr install txfonts
  - tlmgr install newtx
  - tlmgr install geometry
  - tlmgr install ccaption
  - tlmgr install quotchap
  - tlmgr install tex-gyre
  - tlmgr install tocbibind
  - tlmgr install graphics
  - tlmgr install amsmath
  - tlmgr install amsfonts
  - tlmgr install hyperref
  - tlmgr install fontaxes 
  
script:
# use xelatex to convert .tex to .pdf
# of course we could use pandoc for this also, but pdflatex generates nicer PDFs
  - xelatex -interaction=nonstopmode thesis.tex
  - bibtex thesis
  - xelatex -interaction=nonstopmode thesis.tex || true
  - xelatex -interaction=nonstopmode thesis.tex || true  

#after_success:
deploy:

# provider releases means GitHub Releases
  provider: releases
  api_key:
      secure: MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAxEKXlNwT52YJAP3t4egv\nE498zEiZ5QILTLQ41Sz1u427IxOJ8/gAcVHTopWLG7mjzSkSAfgewNY6OLE/H3Rv\nRIfYMl/xpYnXEKV8GvmOihTJc2JX4D9JK16UHa3RRt8ilGSzDGONVjxcv2TfhuCe\nS2BIaIDyglU7iL26Dgg/KR3Yfmp2hQK0C7irQ/wVfMOdsTH1oyAdnCjjmJtX0EQb\nxFxH+YIsTvw0EA8C2AW7AbTeHJlgVnUcSTv/Aa7Xjz3akod54KyrLb709O/ojE22\nYVIkwGO64F1RSqbBlWt1FS0a3bGDouy4kvXU38QUg2/cyHTzqVPb9tl4u7wG4Qdb\nvvDXbG3kYWfnrFHfCCNNSoMdV6a88AN5xJq0UqyLpYhXgh7+OMaNVqJKmkVbZqnb\nVwJe2AJvMowWiZlwpzfMp9sZSaS43QU+tqMD5iYoebvdiZMz00pu4ZloyTUdgvYp\noU1ZVlixNhe+FYp6/djpR9Oon7ZmBXWYniMOKNTC+ZtTQFGz5RNdi5DKw/Hx2fcp\nwfw+OU8R774gXN0Udt1rpnS5ERboY4eUhJfwMl3ZK3HWmYBPpSCDTHA2kMiYcyhU\nLpltTLWwD8rksmMPpJVL8p73mnCs2odLMQeU3RNETfyOV4vAVwf/gZGiC/Mwao4C\napz3JnKaqpH8GYK7vuraQS0CAwEAAQ=
# the list of files to upload
  file: 
    - "thesis.pdf"
  skip_cleanup: true
